modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="balanced_crates"
version="1.0.0."
displayName="Balanced Crates"
credits="This mod was created by _nystylecheesecake_"
displayURL="https://https://github.com/nystylecheesecake/balanced_crates"
logoFile="logo.png"
authors="_nystylecheesecake_"
description='''
Nifty storage blocks that also make great decorations.
'''

[[dependencies.balanced_crates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




