modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="balanced_crates"
version="1.0.10"
displayName="Balanced Crates"
credits="Mod by _nystylecheesecake_  / Created with MCreator"
displayURL="https://https://github.com/nystylecheesecake/balanced_crates"
logoFile="logo.png"
authors="_nystylecheesecake_"
description='''
Nifty storage blocks that also make great decorations.
'''

[[dependencies.balanced_crates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




